version: "3.9"

services: 
  ui-dev:
    build:
      context: .
      target: dev
    restart: always
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3001:3000

  production:
    image: nginx:alpine3.18
    build:
      context: .
      target: build
    restart: always
    ports:
      - 80:80
    logging:
      driver: "json-file"
      options:
        max-size: "1m"

networks:
  follow-network:
    driver: bridge